spring:
  #????????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liuxianglitian
    username: root
    password: 980617
#mybatiis??
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true




#spring??????
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG


