DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS courses;

CREATE TABLE courses (
    course_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE students (
    student_id   INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    student_name VARCHAR(50) NOT NULL,
    gender       TINYINT NOT NULL,
    birth_date   DATE NOT NULL,
    class_id     INT NOT NULL,
    phone        VARCHAR(50) NOT NULL
);

CREATE TABLE scores (
    score_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT NOT NULL,
    course_id  INT NOT NULL,
    score      DECIMAL(5, 2) NOT NULL
);
